#!/bin/sh

bspc config border_width 1

#bspc config normal_border_color "#1D1F21"
bspc config normal_border_color "#747474"
bspc config active_border_color "#4a4e54"
bspc config focused_border_color "#e6e6e6"
bspc config presel_feedback_color "#e6e6e6"

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config window_gap 0 
bspc config gapless_monocle true
bspc config focus_by_distance true

bspc monitor -d 1 2 3 4 5 

# Get background up
source ~/.fehbg

# Start compton
compton --config ~/.config/compton/compton.conf -b

